### ISSUE TITLE
typo in hammer spoon initialisation via terminal command

### ISSUE THREAD

**Issue by martinengelke** [franzbu/EnhancedSpaces.spoon#1]
`echo -e "local EnhancedSpaces = hs.loadSpoon('EnhancedSpaces')\nEnhancedSpaces:new({\nmSpaces = { '1', '2', '3' }, -- default { '1', '2', '3' }\nstartmSpace = 'E', -- default 2\n})" >> ~/.hammerspoon/init.lua`

At first I recognised, that this appendix is just not aware of having a linebreak at start, so It just continued my last line of code.

Secondly there is no mSpace E created in this configuration, but you are setting it as the startmSpace. 

Could cause Errors.

**Comment by franzbu** [comment]
Thank you, fixed.
