### ISSUE TITLE
Got some errors due to first initialisation 

### ISSUE THREAD

**Issue by martinengelke** [franzbu/EnhancedSpaces.spoon#2]
2024-11-06 14:16:10: *** ERROR: ...ngelke/.hammerspoon/Spoons/EnhancedSpaces.spoon/init.lua:539: attempt to index a nil value (field '?')
stack traceback:
	...ngelke/.hammerspoon/Spoons/EnhancedSpaces.spoon/init.lua:539: in function 'winPresent'
	...ngelke/.hammerspoon/Spoons/EnhancedSpaces.spoon/init.lua:502: in function 'createToggleRefMenu'
	...ngelke/.hammerspoon/Spoons/EnhancedSpaces.spoon/init.lua:381: in function 'refreshMenu'
	...ngelke/.hammerspoon/Spoons/EnhancedSpaces.spoon/init.lua:367: in function 'EnhancedSpaces.new'
	/Users/martinengelke/.hammerspoon/init.lua:261: in main chunk
	[C]: in function 'xpcall'
	...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:723: in function 'hs._coresetup.setup'
	(...tail calls...)
2024-11-06 14:16:10: 14:16:10 ERROR:   LuaSkin: hs.application.watcher callback: ...ngelke/.hammerspoon/Spoons/EnhancedSpaces.spoon/init.lua:1370: attempt to index a nil value (field '?')
stack traceback:
	...ngelke/.hammerspoon/Spoons/EnhancedSpaces.spoon/init.lua:1370: in function 'refreshWinMSpaces'
	...ngelke/.hammerspoon/Spoons/EnhancedSpaces.spoon/init.lua:195: in local 'fn'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:950: in upvalue 'emit'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:976: in method 'filterEmitEvent'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1010: in method 'emitEvent'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1085: in method 'onScreen'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1078: in method 'inCurrentSpace'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1270: in method 'getCurrentSpaceAppWindows'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1038: in field 'created'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1400: in upvalue 'appWindowEvent'
	...	(skipping 4 levels)
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1400: in upvalue 'appWindowEvent'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1264: in method 'getCurrentSpaceAppWindows'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1038: in field 'created'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1400: in upvalue 'appWindowEvent'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1264: in method 'getCurrentSpaceAppWindows'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1038: in field 'created'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1400: in upvalue 'appWindowEvent'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1264: in method 'getCurrentSpaceAppWindows'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1231: in method 'getAppWindows'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1225: in field 'new'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1424: in function <...n.app/Contents/Resources/extensions/hs/window_filter.lua:1410>
	(...tail calls...)
2024-11-06 14:16:14: 14:16:14 ERROR:   LuaSkin: hs.timer callback error: ...ngelke/.hammerspoon/Spoons/EnhancedSpaces.spoon/init.lua:1514: attempt to perform arithmetic on a nil value (global 'heightMB')
stack traceback:
	...ngelke/.hammerspoon/Spoons/EnhancedSpaces.spoon/init.lua:1514: in function 'moveMiddleAfterMouseMinimized'
	...ngelke/.hammerspoon/Spoons/EnhancedSpaces.spoon/init.lua:196: in local 'fn'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:950: in upvalue 'emit'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:976: in method 'filterEmitEvent'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1010: in method 'emitEvent'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1085: in method 'onScreen'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1078: in method 'inCurrentSpace'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1270: in method 'getCurrentSpaceAppWindows'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1038: in field 'created'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1400: in upvalue 'appWindowEvent'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1264: in method 'getCurrentSpaceAppWindows'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1231: in method 'getAppWindows'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1225: in field 'new'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1424: in upvalue 'startAppWatcher'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1429: in function <...n.app/Contents/Resources/extensions/hs/window_filter.lua:1428>
2024-11-06 14:17:26: 14:17:26 ** Warning:   wfilter: loginwindow (0) is STILL not registered
2024-11-06 14:17:26: 14:17:26 ** Warning:   wfilter: loginwindow (0) is STILL not registered

**Comment by martinengelke** [comment]
Works for now but Errors continuing:

2024-11-06 14:20:54: 14:20:54 ERROR:   LuaSkin: ...ngelke/.hammerspoon/Spoons/EnhancedSpaces.spoon/init.lua:1514: attempt to perform arithmetic on a nil value (global 'heightMB')
stack traceback:
	...ngelke/.hammerspoon/Spoons/EnhancedSpaces.spoon/init.lua:1514: in function 'moveMiddleAfterMouseMinimized'
	...ngelke/.hammerspoon/Spoons/EnhancedSpaces.spoon/init.lua:196: in local 'fn'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:950: in upvalue 'emit'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:976: in method 'filterEmitEvent'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1010: in method 'emitEvent'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1085: in method 'onScreen'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1078: in method 'inCurrentSpace'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1270: in method 'getCurrentSpaceAppWindows'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1038: in field 'created'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1400: in upvalue 'appWindowEvent'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1313: in method 'focusChanged'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1406: in function <...n.app/Contents/Resources/extensions/hs/window_filter.lua:1374>
2024-11-06 14:20:56: 14:20:56 ERROR:   LuaSkin: ...ngelke/.hammerspoon/Spoons/EnhancedSpaces.spoon/init.lua:1514: attempt to perform arithmetic on a nil value (global 'heightMB')
stack traceback:
	...ngelke/.hammerspoon/Spoons/EnhancedSpaces.spoon/init.lua:1514: in function 'moveMiddleAfterMouseMinimized'
	...ngelke/.hammerspoon/Spoons/EnhancedSpaces.spoon/init.lua:196: in local 'fn'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:950: in upvalue 'emit'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:976: in method 'filterEmitEvent'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1010: in method 'emitEvent'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1085: in method 'onScreen'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1070: in method 'visible'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1060: in method 'unminimized'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1364: in upvalue 'windowEvent'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1390: in function <...n.app/Contents/Resources/extensions/hs/window_filter.lua:1389>
2024-11-06 14:22:44: 14:22:44 ERROR:   LuaSkin: ...ngelke/.hammerspoon/Spoons/EnhancedSpaces.spoon/init.lua:1514: attempt to perform arithmetic on a nil value (global 'heightMB')
stack traceback:
	...ngelke/.hammerspoon/Spoons/EnhancedSpaces.spoon/init.lua:1514: in function 'moveMiddleAfterMouseMinimized'
	...ngelke/.hammerspoon/Spoons/EnhancedSpaces.spoon/init.lua:196: in local 'fn'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:950: in upvalue 'emit'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:976: in method 'filterEmitEvent'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1010: in method 'emitEvent'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1085: in method 'onScreen'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1078: in method 'inCurrentSpace'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1270: in method 'getCurrentSpaceAppWindows'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1038: in field 'created'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1400: in upvalue 'appWindowEvent'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1313: in method 'focusChanged'
	...n.app/Contents/Resources/extensions/hs/window_filter.lua:1406: in function <...n.app/Contents/Resources/extensions/hs/window_filter.lua:1374>
2024-11-06 14:23:47: -- Loading extension: geometry

**Comment by franzbu** [comment]
Could it be that you opened/closed a window while EnhancedSpaces was starting?

**Comment by martinengelke** [comment]
No I was just waiting waiting an watching for the beachball, I may tried to click on the Hammerspoon icon *shame on me*.
But it took like 3 minutes ^^ and I have no patience  …

**Comment by martinengelke** [comment]
Did I destroy something?

**Comment by franzbu** [comment]
No worries, even though EnhancedSpaces still throws some errors that need ironing out, it runs stable on my Mac.

**Comment by martinengelke** [comment]
I keep continuing, no worries.

Future step: implementation in my launcher via terminal "hs - c ...", so that I can directly send them from the launcher to an assigned space, maybe already in a given format.

recommendation: https://albertlauncher.github.io

**Comment by franzbu** [comment]
v0.9.26 (hopefully) fixes these error messages (which shouldn't have affected functionality)
