### ISSUE TITLE
Suggestion: Cycle trough (predefined) grid + introduce swappable positions, example given

### ISSUE THREAD

**Issue by martinengelke** [franzbu/EnhancedSpaces.spoon#4]
Instead of pressing a modifierKey + 0 … 9, o, p I would like to cycle through a (predefined) layout in a left, right, up, and down  manner (custom keys, vim-like hjkl).

I can't just remember all the different possibilities adhoc but if I want to swap two windows I would like to just throw one down and the other one up. 
_OR:_ It would be even easier if they would just recognise another window at this position and swap their position by themselves. 

### Comparison:

**For now swapping means:**
1. bringing first window to the other side -> key combo
2. choosing the second window (out of many other ones), since its now hidden behind the first one -> key combo
3. bringing second window to the other side -> key combo 

**My suggestions:**
1. Stay active on the first window and cycle it to its new position. -> key combo
2. As soon as you release the modifierCylceKey (not the hjkl ones, since you have to release them in order to bring your window in position), the window will snap and the one which was there before goes to the other place

Since I am most of the time working in a specified environment, it would be then fine to define a certain pattern I can cycle trough which means I could just drop some of the grid orientations in favour to have a faster cycling. So they should just cycle through the predefined ones like in modifierSnapKeys().

For that the window **DOES NOT** have to be completely aware of its position and size in the grid and if it's left, right, up or down to another one (and which one), what is more like a function of a _tiling manager_ …

You just have to make sure, that pressing moveRightKey and moveLeftKey is _increasing/decreasing_ the grid **number** in the (predefined) grid and pressing the moveUpKey and moveDownKey is _increasing/decreasing_ the grid **letter** in the (predefined) grid. 

Therefore the window is cycling through a defined array of positions until you release the modifierKey. Then it will take that grid value and the one, which was assigned with that grid value already will move to the freed slot.

**Edit**: just realised that the grid is not like 

a1 a2 a3
b1 b2 b3
c1 c2 c3

which I was assuming at time of writing.
So my description just makes sense for that. But you got an idea of what I was thinking about. 

**E.g., for**
```
  modifierSnapKeys = {
    -- modifierSnapKey1
    {{'a2','j'},{'b11','k'},{'c5','l'}},
    -- modifierSnapKey2
    {},
    -- modifierSnapKey3
    {},
  },
```
you are just able to cycle this three configurations. 

In favour you want to have two windows laying on top of each other, someone should be able to turn this behaviour off.

**Comment by franzbu** [comment]
I like your idea. I'll have to think about it and will get back to you.

**Comment by franzbu** [comment]
Please test `v0.9.28_prerelease`:

After stopping Hammerspoon and renaming `~/.hammerspoon/Spoons/EnhancedSpaces.spoon/init.lua` to `init.lua.org`,
 unzip the attached file `init.lua.zip` and move the resulting `init.lua` into the folder `~/.hammerspoon/Spoons/EnhancedSpaces.spoon/`

After restarting Hammerspoon, you should be able to use `Ctrl` and `Escape` for choosing a window from the current mSpace to swap places with the currently active window. Pressing additionally `Shift` you can cycle the list in reverse order.

In case you'd like to choose different keyboard shortcuts, use the following lines in your `init.lua`:

``` lua
  swapModifier = { 'ctrl' }, -- default: { 'ctrl' }
  swapKey = 'escape', -- default: 'escape'
```

Let me know how this works for you.

[init.lua.zip](https://github.com/user-attachments/files/17679843/init.lua.zip)

**Comment by martinengelke** [comment]
I will try it out later this evening.

**Comment by martinengelke** [comment]
Typo (swawKey instead of swapKey)

**Comment by martinengelke** [comment]
switching back and forth is not always working maybe 1 of 10 is missing. 
edit: it is just changing the focus

```
2024-11-09 12:31:12: ____________ released ____________
2024-11-09 12:31:12: ____________ swapWindows ____________
2024-11-09 12:31:12: win1: Finder
2024-11-09 12:31:12: win2: Safari
2024-11-09 12:31:13: ____________ released ____________
2024-11-09 12:31:13: ____________ swapWindows ____________
2024-11-09 12:31:13: win1: Safari
2024-11-09 12:31:13: win2: Finder
2024-11-09 12:31:14: ____________ released ____________
2024-11-09 12:31:14: ____________ swapWindows ____________
2024-11-09 12:31:14: win1: Finder
2024-11-09 12:31:14: win2: Safari
2024-11-09 12:31:14: ____________ released ____________
2024-11-09 12:31:14: ____________ swapWindows ____________
2024-11-09 12:31:14: win1: Safari
2024-11-09 12:31:14: win2: Finder
2024-11-09 12:31:15: ____________ released ____________
2024-11-09 12:31:15: ____________ swapWindows ____________
2024-11-09 12:31:15: win1: Finder
2024-11-09 12:31:15: win2: Safari
2024-11-09 12:31:16: ____________ released ____________
2024-11-09 12:31:16: ____________ swapWindows ____________
2024-11-09 12:31:16: win1: Safari
2024-11-09 12:31:16: win2: Finder
2024-11-09 12:31:16: ____________ released ____________
2024-11-09 12:31:16: ____________ swapWindows ____________
2024-11-09 12:31:16: win1: Finder
2024-11-09 12:31:16: win2: Finder
2024-11-09 12:31:17: ____________ released ____________
2024-11-09 12:32:17: ____________ released ____________
2024-11-09 12:32:17: ____________ swapWindows ____________
2024-11-09 12:32:17: win1: Safari
2024-11-09 12:32:17: win2: Safari
```


Edit:

I recognised that if the windows are not switching, instead the focus does, if that helps.

**Comment by franzbu** [comment]
What happens when it is missing?

**Comment by martinengelke** [comment]
changing the mSpaces via the menubar icon is reproducable causing a glitch
(changing and changing back)

<img width="738" alt="Bildschirmfoto 2024-11-09 um 12 37 35" src="https://github.com/user-attachments/assets/c370278a-e1b4-4191-8471-55077a345508">

**Comment by franzbu** [comment]
I've made some changes, please give it a try:

[init.lua.zip](https://github.com/user-attachments/files/17687092/init.lua.zip)

**Comment by martinengelke** [comment]
The UI could be a bit less distractive (the small preview could be a bit bigger and the second one is maybe not neccessary). 

I was rather thinking about cycling through all the apps live, so that every app gets in front when you cycle over it, and then if you release it snaps to that position and stays focused. For now you sometimes have to guess the position of the windows since its also cycling through background ones. 
 
In general it would be useful to keep the app in front which is switched. Your algorithm is now always performing an app switch.

**Comment by martinengelke** [comment]
random window swapping bug still appears, look my updated comment.

**Comment by franzbu** [comment]
> The UI could be a bit less distractive (the small preview could be a bit bigger and the second one is maybe not neccessary).
> 
> I was rather thinking about cycling through all the apps live, so that every app gets in front when you cycle over it, and then if you release it snaps to that position and stays focused. For now you sometimes have to guess the position of the windows since its also cycling through background ones.
> 
> In general it would be useful to keep the app in front which is switched. Your algorithm is now always performing an app switch.


This should keep the focus correct. 

I cannot reproduce your swapping error, but have made some changes. Let me know if it solves the issue.

[init_v0.9.28_pre3.lua.zip](https://github.com/user-attachments/files/17687165/init_v0.9.28_pre3.lua.zip)

**Comment by martinengelke** [comment]
btw.: swapping is incredible fast and like magic :)

**Comment by martinengelke** [comment]
2024-11-09 13:04:56: -- Loading extension: alert
2024-11-09 13:04:56: -- Done.
2024-11-09 13:05:09: -- Loading extension: timer
2024-11-09 13:05:09: _____ win 1 _____: Hammerspoon
2024-11-09 13:05:09: ____ win 2 ______: Terminal
2024-11-09 13:05:10: _____ win 1 _____: Hammerspoon
2024-11-09 13:05:10: ____ win 2 ______: Hammerspoon
2024-11-09 13:05:11: _____ win 1 _____: Terminal
2024-11-09 13:05:11: ____ win 2 ______: Hammerspoon
2024-11-09 13:05:12: _____ win 1 _____: Terminal
2024-11-09 13:05:12: ____ win 2 ______: Hammerspoon
2024-11-09 13:05:13: _____ win 1 _____: Terminal
2024-11-09 13:05:13: ____ win 2 ______: Hammerspoon
2024-11-09 13:05:14: _____ win 1 _____: Terminal
2024-11-09 13:05:14: ____ win 2 ______: Hammerspoon
2024-11-09 13:05:15: _____ win 1 _____: Terminal
2024-11-09 13:05:15: ____ win 2 ______: Hammerspoon
2024-11-09 13:05:15: _____ win 1 _____: Terminal
2024-11-09 13:05:15: ____ win 2 ______: Hammerspoon
2024-11-09 13:05:16: _____ win 1 _____: Terminal
2024-11-09 13:05:16: ____ win 2 ______: Hammerspoon
2024-11-09 13:05:17: _____ win 1 _____: Terminal
2024-11-09 13:05:17: ____ win 2 ______: Hammerspoon
2024-11-09 13:05:17: _____ win 1 _____: Terminal
2024-11-09 13:05:17: ____ win 2 ______: Hammerspoon
2024-11-09 13:05:18: _____ win 1 _____: Terminal
2024-11-09 13:05:18: ____ win 2 ______: Hammerspoon
2024-11-09 13:05:19: _____ win 1 _____: Terminal
2024-11-09 13:05:19: ____ win 2 ______: Hammerspoon
2024-11-09 13:05:19: _____ win 1 _____: Terminal
2024-11-09 13:05:19: ____ win 2 ______: Hammerspoon
2024-11-09 13:05:20: _____ win 1 _____: Terminal
2024-11-09 13:05:20: ____ win 2 ______: Hammerspoon
2024-11-09 13:05:20: _____ win 1 _____: Terminal
2024-11-09 13:05:20: ____ win 2 ______: Hammerspoon
2024-11-09 13:05:21: _____ win 1 _____: Terminal
2024-11-09 13:05:21: ____ win 2 ______: Hammerspoon
2024-11-09 13:05:22: _____ win 1 _____: Terminal
2024-11-09 13:05:22: ____ win 2 ______: Hammerspoon
2024-11-09 13:05:22: _____ win 1 _____: Terminal
2024-11-09 13:05:22: ____ win 2 ______: Terminal

**Comment by martinengelke** [comment]
I've unloaded my own init.lua as well. Its pure EnhancedSpaces :-p

Edit: 
It's nice, that you can now swap windows over the menu bar without influencing your actual focus! Didn't thought about that, but can be a benefit to switch between research windows while writing an article.

Edit2: 
menubar glitch seems to be gone as well.

**Comment by franzbu** [comment]
You're swapping a couple of times a second. ATM, I cannot think of anything else except adding a delay to make it impossible to switch that fast, which eventually leads to a hiccup. 

However, I think that practically speaking it is not necessary to switch that fast that often in a row. Apart from that, a delay would take away the feeling of immediacy. So I'd rather keep it that way, what do you think?

**Comment by martinengelke** [comment]
If it's just because of the speed I would not care – like you said it's not a realistic scenario.
No artificial throttling ^^

**Comment by franzbu** [comment]
> If it's just because of the speed I would not care – like you said it's not a realistic scenario. No artificial throttling ^^

That's right.

**Comment by martinengelke** [comment]
I mean if I want to rearrange some windows on my desktop it could be nice to do that as fast as possible. Maybe you will find out some day how to improve that. 

I tried to give hammerspoon like 2 or 3 seconds in between changing and it can be annoying, … 

**BUUUT** the most annoying part of that is, that if the error happens, the focus is instead switching.
So I have to navigate back and for example cmd + tab does not get you back if it was the hammerspoon console (I think the hammerspoon console is not always recognised, doesn't even appear in my dock).

**Comment by martinengelke** [comment]
```
2024-11-09 13:17:38: _____ win 1 _____: Hammerspoon
2024-11-09 13:17:38: ____ win 2 ______: Finder
2024-11-09 13:17:41: _____ win 1 _____: Hammerspoon
2024-11-09 13:17:41: ____ win 2 ______: Safari
2024-11-09 13:17:44: _____ win 1 _____: Hammerspoon
2024-11-09 13:17:44: ____ win 2 ______: Finder
2024-11-09 13:17:45: _____ win 1 _____: Hammerspoon
2024-11-09 13:17:45: ____ win 2 ______: Finder
2024-11-09 13:17:58: _____ win 1 _____: Hammerspoon
2024-11-09 13:17:58: ____ win 2 ______: Finder
2024-11-09 13:18:00: _____ win 1 _____: Hammerspoon
2024-11-09 13:18:00: ____ win 2 ______: Hammerspoon
2024-11-09 13:18:03: _____ win 1 _____: Hammerspoon
2024-11-09 13:18:03: ____ win 2 ______: Finder
2024-11-09 13:18:05: _____ win 1 _____: Hammerspoon
2024-11-09 13:18:05: ____ win 2 ______: Finder
2024-11-09 13:18:07: _____ win 1 _____: Finder
2024-11-09 13:18:07: ____ win 2 ______: Hammerspoon
2024-11-09 13:21:43: _____ win 1 _____: Safari
2024-11-09 13:21:43: ____ win 2 ______: Hammerspoon
2024-11-09 13:21:46: _____ win 1 _____: Safari
2024-11-09 13:21:46: ____ win 2 ______: Hammerspoon
2024-11-09 13:21:48: _____ win 1 _____: Safari
2024-11-09 13:21:48: ____ win 2 ______: Safari
2024-11-09 13:21:53: _____ win 1 _____: Safari
```

**Comment by franzbu** [comment]
I'll give it some thought, maybe there is something that can be done.

**Comment by martinengelke** [comment]
**Big thank you** anyway for implementing a not that trivial task in just one day. 
Appreciate your effort. 🫶

**Comment by franzbu** [comment]
> **Big thank you** anyway for implementing a not that trivial task in just one day. Appreciate your effort. 🫶

You're welcome. Enjoy and have a great weekend!

**Comment by franzbu** [comment]
> I mean if I want to rearrange some windows on my desktop it could be nice to do that as fast as possible. Maybe you will find out some day how to improve that.
> 
> I tried to give hammerspoon like 2 or 3 seconds in between changing and it can be annoying, …
> 
> **BUUUT** the most annoying part of that is, that if the error happens, the focus is instead switching. So I have to navigate back and for example cmd + tab does not get you back if it was the hammerspoon console (I think the hammerspoon console is not always recognised, doesn't even appear in my dock).

The problem of the fucus shifting in situations where the windows aren't swapped should be solved; please give it a try and let me know whether you still encounter issues on that front. 

The archive also contains the folder 'lib'; make sure to move it to ~/.hammerspoon/Spoons/EnhancedSpaces.spoon/. Back up the old one just in case, as the new version breaks compatibility if you want to go back to a previous version (you can always get that from GitHub, though).

[ESv0.9.31_pre1.zip](https://github.com/user-attachments/files/17690525/ESv0.9.31_pre1.zip)

**Comment by martinengelke** [comment]
I expected some weird behaviour with terminal windows. Cannot oven explain exactly what happens but it seems that in case of a terminal window the swapping is doing unexpected things.

same for getting and sending a terminal window, if there is an existing one already its not possible to send or get one afaics

Edit: Was still on the old version, so give me a moment.

**Comment by martinengelke** [comment]
Ok, I got a new point. 
If I am using a launcher, it appears to be the same. Since I am often wake up a window which is laying behind some other window via spotlight/albertlauncher the window is every then a when not getting invoked to the front.

**Comment by franzbu** [comment]
> Ok, I got a new point. If I am using a launcher, it appears to be the same. Since I am often wake up a window which is laying behind some other window via spotlight/albertlauncher the window is every then a when not getting invoked to the front.

Is the issue regarding the incorrectly focussed window when swapping solved? 

For future reference it might be easier and clearer to open a new 'issue' in case it's unrelated.

Please try the attached pre-release. As there have been additional changes from v0.9.31 onwards, please make sure to use the newest ones from GitHub; you can also find them in the attached folder 'lib'.

Also the issue with slow starting times could be solved in case you'd like to try out your old configuration (even though you've mentioned something about it not being around anymore, right?)

[ESv0.9.32_pre1.zip](https://github.com/user-attachments/files/17690998/ESv0.9.32_pre1.zip)

**Comment by martinengelke** [comment]
I thought it might be connected.

The focus worked fine, except for Terminal windows, maybe its related to the window name (martinengelke — -zsh — 81×24) which has some special chars.


I was not testing the starting time anymore, since I am currently just working with EnhancedSpaces loaded into hammerspoon – I could give it another try though.

**Comment by martinengelke** [comment]
Ok, gave it a try and for now it's blazingly fast. Couple of milliseconds.

**Comment by martinengelke** [comment]
Could we maybe just make the preview optional? It's very distractive. I could even live with just the app icons and if there is more than one window open, just the window names listet below. 
For me in the most cases its very text centric content and I can not get any information out the preview anyway.

**Comment by franzbu** [comment]
> I thought it might be connected.
> 
> The focus worked fine, except for Terminal windows, maybe its related to the window name (martinengelke — -zsh — 81×24) which has some special chars.


I cannot reproduce this behavior. I've created the folder 'üßöö' and switched into it, so it's in the terminal's title; however, I can swap from it and to it without issues. 

Let me know in case you can be more specific.

**Comment by franzbu** [comment]
> Could we maybe just make the preview optional? It's very distractive. I could even live with just the app icons and if there is more than one window open, just the window names listet below. For me in the most cases its very text centric content and I can not get any information out the preview anyway.

Please be more specific.

**Comment by martinengelke** [comment]
https://www.icloud.com/iclouddrive/0c6XAW95X5oKBnK34h9TfITjw#Bildschirmaufnahme_2024-11-10_um_11.11

**Comment by franzbu** [comment]
So the focus stays on the left window, rather than staying with window 2, right? And this only happens with terminal windows? Can you just try to switch to a different folder in one of the terminals, so the title is different, and try again?


Edit: I can reproduce it and will look into it. Thanks for reporting.

**Comment by franzbu** [comment]
Issue with incorrect focus when swapping Terminal windows should be solved with v0.9.31.1. Make sure to update 'window_switcher.lua' from the folder 'lib'

**Comment by martinengelke** [comment]
One more suggestion: You should somehow be able to get back to your original position or escape the command. At the moment it's not possible.

another bug I experienced is regarded to closed windows which are not matched correctly in the term of swapping:

<img width="1512" alt="Bildschirmfoto 2024-11-11 um 08 11 30" src="https://github.com/user-attachments/assets/4a9779b9-95d7-4472-adeb-4243758feb97">

In this case it was a Search/Replace window of an app called OmegaT (Java based), which I just closed after completing the search. 

If I restart Hammerspoon it's gone.

**Comment by martinengelke** [comment]
swapModifier = { 'ctrl' }, -- default: { 'ctrl' }
swapKey = 'escape', -- default: 'escape'

Same suggestion as the other time: Don't bind it at "escape" by default. People are not able to escape the function in that configuration. **I did not find out how to escape anyway, since ESC is not working in general.**

I guess you just implemented alt-tab into your EnhancedSpaces? I recognised that now I have an alt-tab functionality as well, which I would like to turn off. 

It would be also nice to turn off the big previews as well. and stay with the small ones in swapping configuration.

**Comment by franzbu** [comment]
added possibilities to (1) [disable switching between the windows of your current mSpace](https://github.com/franzbu/EnhancedSpaces.spoon/blob/main/README.md#switching-between-windows) and (2) [disable swapping windows](https://github.com/franzbu/EnhancedSpaces.spoon/blob/main/README.md#swapping-windows)

To learn how to change the appearance of the switcher [follow this link](https://github.com/franzbu/EnhancedSpaces.spoon#changing-appearance-of-switcher).

**Comment by martinengelke** [comment]
Sorry for late reply, I was a bit busy.

It looks all quite good. Thank you for this great implementation. 
By time I will try to figure out if I have some more ideas (end of month is always a bit busy).

**Comment by franzbu** [comment]
That is perfectly fine; feedback is welcome but by no means required. I'm glad EnhancedSpaces is working well for you. Good luck with your busy end-of-month schedule!
