### ISSUE TITLE
Possibility to add non modifier keys as modifier? + bug

### ISSUE THREAD

**Issue by martinengelke** [franzbu/EnhancedSpaces.spoon#5]
If I for example choose F18 as e.g. modifierSnap1 EnhancedSpaces is ignoring the modifier at all and just uses the defined modifierSnapKeys, so that the keys getting caught. 

e.g.:

```
    modifierSnap1 = { 'F18' },

    modifierSnapKeys = {
    -- modifierSnapKey1
        {{'a7','1'},{'a1','2'},{'a2','3'}},
     -- modifierSnapKey2
        {},
     -- modifierSnapKey3
        {},
  }
```

I am asking, because I use F18 as my hyper key defined in hyper.lua like:

```
-- A global variable for the Hyper Mode
hyper = hs.hotkey.modal.new({}, 'F17')

-- Enter Hyper Mode when F18 (Hyper/Capslock) is pressed
function enterHyperMode()
  hyper.triggered = false
  hyper:enter()
end

-- Leave Hyper Mode when F18 (Hyper/Capslock) is pressed,
-- send ESCAPE if no other keys are pressed.
function exitHyperMode()
  hyper:exit()
  if not hyper.triggered then
    hs.eventtap.keyStroke({}, 'ESCAPE')
  end
end

hyperBindings = {
                    '1',        --  Workspace 1
                    '2',        -- AeroSpace Workspace 2
                    '3'        -- AeroSpace Workspace 3
                }

for i,key in ipairs(hyperBindings) do
  hyper:bind({}, key, nil, function() hs.eventtap.keyStroke({'cmd','alt','shift','ctrl'}, key)
    hyper.triggered = true
  end)
end

-- Bind the Hyper key
f18 = hs.hotkey.bind({}, 'F18', enterHyperMode, exitHyperMode)
```

Anyway, If I just (accidentally) use another not modifier key like a number or a letter it has the same effect.

**Comment by franzbu** [comment]
I don't know how your setup works, but if `F18` is set up as hyper key, as such it should trigger the four basic modifiers, in which case your line could look like this:

``` lua
modifierSnap1 = { 'cmd', 'alt', 'ctrl', 'shift' },
```

**Comment by martinengelke** [comment]
Yes, you are absolutely right. 
I am registering my F18 as "cmd alt ctrl shift" if it is pressed in combination with a certain key/keycombo in an own config table. 
Some tools I can directly trigger with F18 (remapped to capslock) and for the other ones, not accepting those keys I simulate a hyper key keystroke. 

unfortunately I cleaned my init.lua today and uhmmm yes, this line got lost:

hyper.start(config)

damn, took me some time, to figure it out.
thanks anyway, maybe its helpful for other people.

**Comment by martinengelke** [comment]
But anyway you should check the modifierSnap1 is really a modifier and not another random key. Since it's not working then and the snapKey is just getting caught by your .spoon. I could not write 1,2,3 anymore until I made a change to the modifierSnap1 to cmd+alt again.

**Comment by franzbu** [comment]
Thank you; I will point it out explicitly in the documentation that it is necessary to use one of the four modifiers.
