### ISSUE TITLE
Launchers, Slideovers, Clipboard Tools, Notifications shouldn't be focused as an frontmost window

### ISSUE THREAD

**Issue by martinengelke** [franzbu/EnhancedSpaces.spoon#6]
I figured out, that e.g. Maccy or my launcher app is focused if I invoke them, which is not meant to be like that to fulfil their task. 
So the main app which is intended to stay in focus for copying stuff inside is not available anymore.

**Focus**: defined as having their name in the menubar.
Which is essential for launchers and command pallet tools like paletro (I build my own one since Hammerspoon has a neat feature to retrieve menu entries. It fetches entries as JSON and sends them to my launcher).

First time I recognised by an incoming mail. My window just lost focus and I couldn't continue writing.

**Comment by martinengelke** [comment]
Still a bug on [ESv0.9.32_pre1.zip](https://github.com/user-attachments/files/17690998/ESv0.9.32_pre1.zip)

**Comment by martinengelke** [comment]
Maybe we could just implement an Exception List for certain Apps which should not work together with EnhancedSpaces since the ones I mentioned are all intended to float anyway.

**Comment by franzbu** [comment]
I use Maccy and it works as expected with EnhancedSpaces; it needs getting focus to choose which text snippet to copy. What exactly is it that is not working for you?

Hammerspoon generally disregards anything that is not a window, such as dialogs, and Hammerspoon's filters already include a series of exceptions. EnhancedSpaces can add exceptions of its own, and I will look into it. However, as the upcoming weeks will be busy, this may take a little while.

That being said, the concept of floating windows belongs to tiling window managers, as with EnhancedSpaces all windows are floating ones, i.e., you can move them around freely and they remain where you put them. The point with EnhancedSpaces is one of correctly focussing windows, and in the cases you've mentioned the workaround is to press cmd-tab, right?

**Comment by franzbu** [comment]
Please check whether the attached pre-release solves (some of) these issues. Make sure to either use the attached files from the folder 'lib' or the newest ones from GitHub.

[ESv0.9.33_pre1.zip](https://github.com/user-attachments/files/17698739/ESv0.9.33_pre1.zip)

**Comment by martinengelke** [comment]
Ok, I'll try out.

**Comment by martinengelke** [comment]
[ESv0.9.33_pre1.zip](https://github.com/user-attachments/files/17698739/ESv0.9.33_pre1.zip) solved terminal, launcher and maccy issue, but I just recognised, that for example the settings of maccy just disappears somewhere in the background now, if I invoke it via CMD + ,

**Comment by franzbu** [comment]
I've made some changes that should, for example, get the settings of Maccy to the foreground:

[ESv0.9.33_pre2.zip](https://github.com/user-attachments/files/17699546/ESv0.9.33_pre2.zip)

**Comment by martinengelke** [comment]
Now it appears to get maccy as the frontmost application as well as the settings window (which is still not focussed) in the foreground again. 
As a 'side effect' an app switch is bringing up all the app windows in the foreground as well.
For example I had a finder window fullscreen, performed a CMD TAB to terminal and two windows, properly arranged showed up. Is it a feature rather than a bug? ^^

**Comment by franzbu** [comment]
Great! Let's call it a feature, then :)

**Comment by martinengelke** [comment]
But we should care about getting apps like maccy back to the background, since its not fulfilling its function if it gets the frontmost position, same for paletro and my launcher (which I use for snippets) :)

I can not imagine what's happening behind the scenes and which tricks do you have to use to recognise a window of a clipboard like app to be backed and a settings window to get in front. 
I can just suggest again to allow the user to fill up configurations to make sure certain windows, apps etc. are working well. It's a bit more of manual work (for the user), but you may not able to get every configuration by default. (that's why I gave you the idea in reddit of regex).

**Comment by franzbu** [comment]
> But we should care about getting apps like maccy back to the background, since its not fulfilling its function if it gets the frontmost position, same for paletro and my launcher (which I use for snippets) :)
> 
Please explain what you mean by "getting apps like maccy back to the background"; as I've already said, Maccy behaves fine here.


> I can not imagine what's happening behind the scenes and which tricks do you have to use to recognise a window of a clipboard like app to be backed and a settings window to get in front. I can just suggest again to allow the user to fill up configurations to make sure certain windows, apps etc. are working well. It's a bit more of manual work (for the user), but you may not able to get every configuration by default. (that's why I gave you the idea in reddit of regex).

I will see what I can do.

**Comment by martinengelke** [comment]
https://www.icloud.com/iclouddrive/06apPWVCmEkta1yD55dQSTYTA#Bildschirmaufnahme_2024-11-11_um_11.36

**Comment by franzbu** [comment]
I've double-checked with Maccy, and it behaves perfectly fine. No filter is triggered when Maccy's window with its text snippets is opened (I use cmd-shift-v). 

Maccy's window gets focused, and selecting one entry with keyboard or mouse returns the focus back to the previously focused window and the selected text snippet is pasted as expected. 

Please check your setup, and make sure you're using the newest version of EnhancedSpaces, as of now v0.9.33.

Here my relevant settings:

<img width="654" alt="Screenshot 2024-11-12 at 4 34 53 PM" src="https://github.com/user-attachments/assets/a9138060-4e45-4f41-9b4d-6506576aadb6">

**Comment by franzbu** [comment]
I've implemented a possibility to add windows to the list that Hammerspoon disregards. To do so, add the following lines to the configuration of EnhancedSpaces in your `init.lua`:

``` lua
  -- window_filter.lua: windows to disregard
  SKIP_APPS_TRANSIENT_WINDOWS = {
    'Spotlight', 'Notification Center', 'loginwindow', 'ScreenSaverEngine', 'PressAndHold',
    'PopClip','Isolator', 'CheatSheet', 'CornerClickBG', 'Alfred', 'Moom', 'CursorSense Manager',
    'Music Manager', 'Google Drive', 'Dropbox', '1Password mini', 'Colors for Hue', 'MacID',
    'CrashPlan menu bar', 'Flux', 'Jettison', 'Bartender', 'SystemPal', 'BetterSnapTool', 'Grandview', 'Radium',
    'MenuMetersApp', 'DemoPro', 'DockHelper',
  },
```
With a few exceptions ('DockHelper', 'Alfred',) this is the original list. 

Add application names you want Hammerspoon to disregard to the list in accordance with the given formatting ('application name' followed by a comma).

Make sure to use the files from the attached folder 'lib'.

Please try it out and give feedback.


[ESv0.9.34_pre1.zip](https://github.com/user-attachments/files/17736042/ESv0.9.34_pre1.zip)

**Comment by martinengelke** [comment]
Maccy wasn't working properly for me, but with this list I finally managed it. As well as my launcher application albertlauncher.

**Comment by franzbu** [comment]
Thanks for your feedback.

**Comment by franzbu** [comment]
> Maccy wasn't working properly for me, but with this list I finally managed it. As well as my launcher application albertlauncher.

If you can send me what has to be added to have albertlauncher work correctly, I will add that to the configuration.

**Comment by martinengelke** [comment]
You got me wrong. I just **_added_**

```
SKIP_APPS_TRANSIENT_WINDOWS = {
    'Albert', 'Maccy', 
  },
```

and its fine now. :)

btw.: this launcher is worth having a look (https://albertlauncher.github.io)

**Comment by franzbu** [comment]
Thank you, it's 'Albert' I needed. BTW, you shouldn't remove the applications that are there by default, just add yours.

**Comment by martinengelke** [comment]
Sorry, I just did that for you to have a better overview :) They are still in my config, don't worry. 

I just took the Application name, but some of them do not look like following this pattern. That's why they often use bundleIDs and why I came up with (Regex) patterns. I mean generally in my configuration I would skip every window containing "setting" for cycling.

**Comment by franzbu** [comment]
I can see your point and might look into it at some point. Thanks for the suggestion for albertlauncher.
